# Generated by Django 5.2.3 on 2025-07-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telegram_id',
            new_name='telegram_chat_id',
        ),
    ]
